module.exports = {
	extends: [
		'keystone',
	],
	plugins: [
		'react',
	],
	rules: {
		'react/jsx-boolean-value': 'error',
		'react/jsx-curly-spacing': 'error',
		'react/jsx-equals-spacing': 'error',
		'react/jsx-indent-props': ['error', 'tab'],
		'react/jsx-indent': ['error', 'tab'],
		'react/jsx-key': 'error',
		'react/jsx-no-bind': 'warn',
		'react/jsx-no-duplicate-props': 'error',
		'react/jsx-no-undef': 'error',
		'react/jsx-pascal-case': 'error',
		'react/jsx-uses-react': 'error',
		'react/jsx-uses-vars': 'error',
		'react/jsx-wrap-multilines': 'error',
		'react/no-did-mount-set-state': 'error',
		'react/no-did-update-set-state': 'error',
		'react/no-direct-mutation-state': 'error',
		'react/no-unknown-property': 'error',
		'react/react-in-jsx-scope': 'error',
		'react/self-closing-comp': 'error',
		'react/sort-comp': 'error',
		'react/sort-prop-types': 'error',
	},
};
